name: Android CI

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Create .android folder
      run: mkdir ~/.android
    - name: Install libncurses5
      run: sudo apt update && sudo apt install libncurses5
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew app:packageReleaseUniversalApk
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: app/build
